blank_issues_enabled: true
contact_links:
  - name: Support
    url: https://discord.gg/bkM46A3UgQ
    about: Please ask and answer questions here
  - name: List a token
    url: https://github.com/NiiFi/default-token-list#adding-a-token
    about: Any requests to add a token to NiiFi should go here
