name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Production CDN Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Trigger AWS CodePipeline
        uses: zulhfreelancer/aws-codepipeline-action@v1.0.7
        with:
          aws-region: "eu-west-1"
          aws-access-key: ${{ secrets.AWS_PIPELINE_ACCESS_KEY }}
          aws-secret-key: ${{ secrets.AWS_PIPELINE_SECRET_KEY }}
          pipeline-name: "niifi-uinterface"
