name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Production Deploy
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST_PRODUCTION }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_KEY_PRODUCTION }}
          script: bash /var/uinterface/bin/deploy.sh --production