name: Deploy to staging

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST_STAGING }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_KEY_STAGING }}
          script: sh /var/uinterface/bin/deploy.sh --staging